### ISSUE TITLE
Make Woocommerce variables custom

### ISSUE THREAD

**Issue by justinkruit** [crftwrk/bootscore#12]
A comment I made on commit 289c65e07833929d869489e005fe92c9c198848f:

Is it an idea to create custom variables, that call the Bootstrap variables? So if someone would want to change the colors in their child theme, they just need to change the variable definition.

Either that, or use the fallback in variable calling, so you call a variable that hadn't been made yet, and people can add to change the color easily.

I can write some examples if you want.

**Comment by crftwrk** [comment]
Yes, that seems to be a good idea! If you have already an idea in mind how to solve that, I am happy about your contribution.

**Comment by justinkruit** [comment]
Here is an example of how I imagined it. This way you don't get a long list of variables in the root, and as long as a bscore variable isn't defined it will fall back to the Bootstrap variable.

```
.woocommerce div.product p.price, .woocommerce div.product span.price, .card .price {
    color: var(--bscore-wc-price, --bs-gray);
}
```

I first tried it with a root and all custom variables, but it will just create a very long list of unnecessary variables if the user is not planning to change them.

If you think it's a good idea like this, I can make a pull request for this.

**Comment by crftwrk** [comment]
Yes please, PR is fine. Maybe this can be an option for other colors? Some users prefer CSS overrides instead of compiling an own  Bootstrap.

**Comment by justinkruit** [comment]
What exactly do you mean by that? That people can override default Bootstrap styling? Or do you just mean in parts in bootScore where you call Bootstrap variables?

**Comment by crftwrk** [comment]
I got this working with 2nd variable inside:

```css
.woocommerce div.product p.price, .woocommerce div.product span.price, .card .price {
    color: var(--bscore-wc-price, var(--bs-gray));
}
```

What I mean in previous comment is that many users are not able or do not want to edit Bootstrap with Sass. Instead they using CSS overrides for colors and this can be tricky.

Whats about the idea to provide custom variables for more as a feature? I'm not sure if we should open this box, because possibilities are limited and it will be difficult to remove that later if that's not so good after all. But I'd like to share and love to hear what you think about.

Bootstrap does this:

```css
.bg-primary {
    --bs-bg-opacity: 1;
    background-color: rgba(var(--bs-primary-rgb),var(--bs-bg-opacity))!important;
}
```

We can provide a fallback:

```css
.bg-bscore-primary {
    background-color: var(--bscore-primary, var(--bs-primary)) !important; 
}
```

Set root color in child

```css
:root {
    --bscore-primary: #fe0130;
}
```

Change classes in theme

```html
<p class="bg-bscore-primary p-3 text-white">
    bg-btscr-primary
</p>
```

`bg-*` classes are just used in header.php, footer.php and functions.php.

This work for all `bg-*` and `text-*` classes but not for Sass generated shades or rgb in form focus, checks and alerts. (Still) not work for buttons and body links.

Please check here: https://dev.bootscore.me/custom-color-variables/
